include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AndroidPatternPrefs
AndroidPatternPrefs_FILES = RootListController.m
AndroidPatternPrefs_INSTALL_PATH = /Library/PreferenceBundles
AndroidPatternPrefs_FRAMEWORKS = UIKit
AndroidPatternPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk