name: Build Tweak
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos (Manual)
        run: |
          # We clone manually to avoid the GitHub API rate limit error
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
      - name: Setup iOS SDK
        run: |
          # Ensure the sdks folder is ready and clone the headers
          rm -rf ~/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          make package messages=yes FINALPACKAGE=1
          
      - name: Upload Finished Deb
        uses: actions/upload-artifact@v4
        with:
          name: AndroidPattern-Package
          path: packages/*.deb
