name: Build Tweak
on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos (Manual)
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          
      - name: Setup iOS SDK
        run: |
          rm -rf ~/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks
          
      - name: Install Dependencies
        run: brew install ldid

      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          make package messages=yes FINALPACKAGE=1 SDKPATH=$THEOS/sdks/iPhoneOS14.5.sdk
          
      - name: Upload Finished Deb
        uses: actions/upload-artifact@v4
        with:
          name: AndroidPattern-Package
          path: packages/*.deb
          
